export const UrlConstants: Record<string, string> = {
  ORDERS_URL: '/orders',
  CONTRACTS_URL: '/contracts',
  INVOICES_URL: '/invoices',
  COMMISSION_INVOICES_URL: '/commissions',
  PAYMENTS_URL: '/payments',
  PAYMENTS_BY_CREATION_URL: '/payments/by-creation',
  SHIPMENTS_URL: '/shipments',
  COMMISSION_PAYMENTS_URL: '/commission-payments',
  RECEIVES_URL: '/receives',
  PRODUCTION_URL: '/production',
  TRANSPORT_URL: '/transport',
  TRANSIT_URL: '/transit',
  WAREHOUSE_URL: '/warehouse',
  PRODUCT_REPORT_URL: '/warehouse/product',
  BATCH_REPORT_URL: '/warehouse/batch',
  BATCHES_URL: '/batches',
  CALENDAR_URL: '/calendar',
  COMPANIES_URL: '/companies',
  GOODS_PRODUCT_URL: '/goods/product',
  GOODS_BATCH_URL: '/goods/batch',
  GOODS_BATCHES_URL: '/goods/batches',
  LIBS_DATA_URL: '/store-data',
};
